import LocalizedStrings from 'react-native-localization';
export const LanguageManager = new LocalizedStrings({
  English: {
    onboarding: {
      welcome: 'Welcome to Qubetics Wallet',
      subText: 'Digital money, your future',
      createWallet: 'Create a new wallet',
      importWallet: 'I already have a wallet',
      safeText: 'Safe and Protected',
      trustcrypto: 'Trust our crypto wallet for security and protection.',
      connectTangem: 'Connect Tangem Card',
      nonCustodial: 'Your non-custodial, multi-chain wallet for seamless and secure global payments',
    },
    legal: {
      review:
        'Please review the Qubetics Wallet Terms of Service and Privacy Policy.',
      terms: `I accepted the `,
      privacy: `Privacy Policy`,
      termsservice: `Terms of Service `,
      legal: 'Legal',
    },
    walletName: {
      walletName: 'Wallet Name',
      wallet: 'Wallet',
      enterWalletName: 'Enter Wallet Name',
      enterName: 'Enter Name',
      enterHere: 'Enter here',
      youCanlable:
        'You can label your own wallet and manage multiple wallets here.',
      maxLimit: 'Max Limit:',
      nameWallet: 'Name your wallet',
      thisSecretPhrase: "This secret phrase is the master key to your wallet",
      thisPrivateKey: "These private keys are the master key to your wallet",
      tapOnAll: "Tap on all checkboxes to confirm you understand the importance of your secret phrase",
      ifILose: "If I lose my secret phrase, my funds will be lost forever.",
      keyWallet: "Qubetics Wallet support will NEVER reach out to ask for it.",

      logoutWarning1: "Please back up your seed phrase before logging out to avoid losing access to your wallet.",
      logoutWarning2: "Are you sure you want to log out? Without a backup, you may lose access to your funds.",

    },
    importWallet: {
      importWalletText: 'Import Wallet',
      importPrivate: 'Add Private Key',
      enterPrivateKey: 'Enter Your Private Key',
      importWallet: 'Wallet Name',
      importWalletH1: 'You can label your own wallet and manage multiple wallets here.',
      paste: 'Paste',
      twelveWordSeparated: '12 words separated by single space',
      import: 'Import',
      whatIs: 'What is Secret Phrase?',
      secret: 'Secret Phrases',
    },
    secretPhrase: {
      secretPhrase: 'Write Down Your Seed Phrase',
      writeDown:
        `This is your seed phrase. Write it down on a paper and keep it in a safe place. You'll be asked to re-enter this phrase (in order) on the next step.`,
      doNotShare:
        'DO NOT share your phrase to anyone as this gives full access to your wallet!',
      copy: 'Copy',
      futureWalletSupport:
        'Qubetics Wallet support will NEVER reach out to ask for it.',
      neverShareYour: 'Never share your secret phrase with anyone',
      your12Word:
        'Your 12 word secret phrase is the master key to your wallet, Anyone that has your secret phrase can access and take your crypto.',
      futurerWalletDoesNot:
        'Qubetics wallet does not keep a copy of your secret phrase.',
      unencryptedDigital:
        'Unencrypted digital copies of your secret phrase are NOT recommended. Examples include saving copies on computer, in email, om online accounts, or by taking screenshots.',
      writeDownYour:
        'Write down your secret phrase, and store it in a secure offline location!',
      your12WordSecret:
        'You 12 word secret phrase is only way to recover your wallet. Please store it securely!',
    },
    verifyPhrase: {
      verifySecretPhrase: 'Enter Your Seed Phrase',
      yourSecretPhrase: 'Your Seed Phrase',
      taptheWord:
        'Tap the words to put them next to each other in the correct order.',
    },
    manageWallet: {
      manageWallet: 'Manage Wallet',
      addnewWallet: 'Add Wallet',
      backup: 'Backup Options',
      showRecovery: 'Show Recovery Phrase',
      exportKey: 'Export Private Keys',
      recoveryPhrase: 'Recovery Phrase',
      back: 'Back',
      headerText:
        "This is your seed phrase. Write it down on a paper and keep it in a safe place. You'll be asked to re- enter this phrase(in order) on the next step.",
      copyThePhrases: "Copy the passphrase  and write down these phrases in the correct sequence",

      privateKey: "Private Key",
      keepYourPrivateKey: "Keep your private key safe!"
    },

    walletMain: {
      termsandConditions: 'Terms and Conditions',
      screenshot: 'Screenshots are not Secure',
      newAddress: 'Address 01',
      totalBal: 'Total Balance',
      screenShotMsg:
        'If you take, your Login credentials may be viewed by other apps. You can make a safe backup.',
      iUnder: 'I UNDERSTAND',
      totalValue: 'Total Value',
      send: 'Send',
      receive: 'Receive',
      cards: 'Cards',
      add: 'Add',
      assets: 'Assets',
      noassetsfound: 'No assets found',
      viewAll: 'View All',
      viewLess: 'View Less',
      coin: 'Coin',
      searchOnly: 'Search',
      addUrl: 'Add URL',
      search: 'Search Tokens',
      Noasset: 'No assets found',
      Nodata: 'No data found',
      walletBalance: 'Wallet Balance',
      aboutUs: 'About Us',
      privacyPolicy: 'Privacy Policy',
      Wallet: 'Wallet',
      searchAssets: 'Manage Token',
      welcometoTriskelWallet: `Welcome to\nTriskel Wallet`,
      decentralizedEcosystem:
        'A decentralized ecosystem means only you can access your funds.',
      AccessUsingWeb3Auth: '---- Access using Web3 Auth ----',
      totalInvestedAmount: 'Total Invested Amount',
      amount: 'Amount',
      percentage: 'Percentage',
      addAssetToTheWatchlist: 'Done',
      buy: 'Buy',
      sell: 'Sell',
      addAssetsTOWatchlist: 'Add Assets to the Watchlist'
    },
    alertMessages: {
      crossChainNotSupport: 'Crosschain is not supported',
      priceImactAlert: 'Price Impact is too high',
      processTheTransactionAlert: 'Process the transaction at your own risk',
      enterValidRefCode: 'Enter valid referral code',
      contractSignedSuccess: 'Contract Signed Successfully!',
      areYouSureWantToExist: 'Are you sure want to exit?',
      noassetsfound: 'No active asset found',
      somethingWentWrong: 'Something Went Wrong.',
      firstNameismandatory: 'First Name is mandatory',
      lastNameismandatory: 'Last Name is mandatory',
      phoneNumberismandatory: 'Phone Number is mandatory',
      pleaseEnterValidPhonenumber: 'Please enter valid phone number',
      pleaseenterOTP: 'Please enter OTP',
      pleaseentervalidOTP: 'Please enter valid OTP',
      pleaseVerifyYourOTP: 'Please verify your OTP',
      emailAddressIsMandatory: 'Email address is mandatory',
      pleaseEnterValidEmailAddress: 'Please enter valid email address',
      SomethingwentwrongPleasetryagain:
        'Something went wrong. Please try again.',
      inputlimitexceed: 'Input limit exceed',
      addressMandatory: 'Address is mandatory',
      stateMandatory: 'State is mandatory',
      zipCodeMandatory: 'Zip Code is mandatory',
      genderMandatory: 'Please select Gender',
      minMAxPhoneLenght: 'Phone no. should be of min 7 and max 13 digits',
      otpIsMandatory: 'OTP is mandatory.',
      PleaseentervalidOTP: 'Please enter valid OTP.',
      pleaseEnterValidEmailAddressPeriod: 'Please enter valid email address.',
      copied: 'Copied',
      PleaseactivateTronUSDT: 'Please activate Tron USDT in your wallet.',
      walletAddressCopied: 'Wallet Address Copied!',
      codeCopied: 'Code Copied!',
      YoudonthaveEnoughbalanceAmountTransactionFee:
        "You don't have enough balance (Amount + Transaction Fee)",
      Youdonthaveenoughbalance: "You don't have enough balance",
      youhaveInsufficientBalance: 'You have insufficient balance',
      youhaveInsufficientTrxBalance: 'You have insufficient TRX balance',
      youhaveInsufficientEthBalance: 'You have insufficient ETH balance',
      youhaveInsufficientBnbBalance: 'You have insufficient BNB balance',
      youhaveInsufficientMaticBalance: 'You have insufficient MATIC balance',
      youCanEnterOnlyOneDecimal: 'You can enter only one decimal!',
      pleaseEnterValidAmount: 'Please enter valid amount',
      pleaseEnterAmount: 'Please enter amount',
      youCannotSendToSameAddress: 'You cannot send to same address',
      cannotAddSameAddress: 'You cannot add own address',
      pleaseEnterValidAddress: 'Please enter valid address',
      pleaseEnterWalletAddress: 'Please enter wallet address',
      contactDeletedSuccessfully: 'Contact deleted successfully',
      doYouWantToDeleteContact: 'Do you want to delete contact?',
      doYouWantToDeleteTheContact: 'Do you want to delete the contact?',
      pleaseEnterValidContactName: 'Please enter valid contact name',
      pleaseEnterValidName: 'Please enter valid name',
      enterValidWalletName: 'Enter valid wallet name!',
      pleaseEnterAddress: 'Please enter address',
      pleaseSelectNetwork: 'Please select network',
      pleaseEnterValidWalletAddress: 'Please enter valid wallet address',
      enterCheckerCode: 'Please enter checker code',
      enterWalletName: 'Enter wallet name!',
      contactAddedSuccessfully: 'Contact added successfully',
      thisTransactionIsCurrentlyBeingProcessed:
        'This transaction is currently being processed.',
      transactionFailed: 'Transaction Failed.',
      confirmFingerprint: 'Confirm fingerprint',
      failedtoInitiateTransaction: 'Failed to Initiate Transaction',
      balancetooLowforThisTransaction:
        'Balance is too low for this transaction',
      enterValidBTCaddress: 'Enter valid BTC address',
      copiedToClipboard: 'Copied to Clipboard!',
      enterValidLTCAddress: 'Enter valid LTC address',
      enterValidSolAddress: 'Enter valid Sol address',
      cannotProceed: 'Cannot proceed',
      selectPaymentGatewayToProceed: 'Select Payment Gateway to proceed',
      minimumAmountMustBe: 'Minimum amount must be',
      maximumAmountMustBe: 'Maximum amount must be',
      insufficientBalance: 'Insufficient Balance',
      yourTransactionIsSuccessfullySubmitted:
        'Your transaction is successfully submitted.',
      NoNetworkConnection: 'No network connection',
      pleaseSelectDateOfBirth: 'Please select Date of Birth.',
      pleaseSelectNationality: 'Please select nationality.',
      pleaseEnterDocumentNo: 'Please enter document no.',
      pleaseEnterDocumentExpiry: 'Please enter document expiry no.',
      pleaseEnterEmergencyContact: 'Please enter emergency contact name.',
      pleaseEnterEmergencyNumber: 'Please enter emergency number.',
      pleaseUploadFrontIDphoto: 'Please upload front ID photo',
      pleaseUploadSelfieOfHandHoldingIDcard:
        'Please upload selfie of hand holding ID card.',
      pleaseUploadSignature: 'Please submit your signature.',
      pleaseSaveYourSignature: 'Please save your signature.',
      kycDetailsSubmittedSuccessfully: 'KYC details submitted successfully.',
      grantStoragePermissionInSettings: 'Grant storage permission in settings',
      documentNumberIsMandatory: 'Document number is mandatory',
      documentExpNumberIsMandatory: 'Document expiry number is mandatory',
      emergencyContactIsMandatory: 'Emergency contact is mandatory',
      emergencyNumberMandatory: 'Emergency number is mandatory',
      invalidContractAddress: 'Invalid Contract Address',
      invalidWalletAddress: 'Invalid Wallet Address',
      tokenAlreadyExist: 'Token Already Exist.',
      allFieldsAreMandatory: 'All fields are mandatory.',
      enteredPINDoesNotMatch: 'Entered PIN does not match.',
      PINChangedSuccessfully: 'PIN changed successfully',
      onlyLetters: '(Only letters)',
      valueMustBeGreaterLessThan: 'Value must be either greater or less than',
      pleaseCheckYourNetworkConnection: 'Please check your network connection',
      doYouWantToDeleteBookmarks: 'Do you want to delete bookmarks?',
      selectToDate: 'Select To Date',
      selectFromDate: 'Select From Date',
      invalidDateFilter: 'Invalid date filter',
      noHistoryToDownload: 'No history to download!',
      fileSavedToDownloads: 'File saved to downloads.',
      emailMismatchDoYouWantToSwitchAccount:
        'Email Mismatch!\nDo you want to switch account?\nYour app data will be reset.',
      enterEmail: 'Enter email',
      enterValidEmail: 'Enter valid email',
      Ok: 'Ok',
      wrongPIN: 'Invalid pin entered.',
      cardNumberIsMandatory: 'Card number is mandatory',
      pleaseEnterValidCardNumber: 'Please enter valid card number',
      envelopNumberIsMandatory: 'Envelop number is mandatory',
      linkingNameIsMandatory: 'Linking name is mandatory',
      wantToDeleteThisWallet: 'Are you sure you want to delete this wallet?',
      wantToMakeThisWalletDefault:
        'Are you sure you want to make this wallet default?',
      emailMismatch: 'Email Mismatch!',
      walletAlreadyExists: 'Wallet already exists',
      walletNameAlreadyExists: "wallet name already exists",
      priceAlertDeletedSuccessfully: 'Price alert deleted successfully',
      WantToDeleteThisPriceAlert: 'Do you want to delete this price alert?',
      enableCoinsToAddPriceAlerts: 'Enable coins to add price alerts',
      systemSecurityIsNotEnabled: 'System security is not enabled.',
      sessionTimeout: 'Session Timeout',
      willBeLoggedOutFromTheApp:
        'You will be logged out from the app.\nDo you want to continue?',
      provinceIsMandatory: 'Province is mandatory',
      cityIsMandatory: 'City is mandatory',
      streetAddressIsMandatory: 'Street Address is mandatory',
      postcodeIsMandatory: 'Postcode is mandatory',
      emailIsMandatory: 'Email is mandatory',
      pleaseEnterReferralCode: 'Please enter referral code',
      watchlistUpdatedSuccessfully: 'Watchlist updated successfully',
      wantToRemoveThisAssetFromWatchlist:
        'Do you want to remove this asset from watchlist?',
      addTokenFromAddCustomToken:
        'Please add this token from add custom token screen to enable swapping',
      addTokenFromAddCustomTokenGasless:
        'No gasless tokens are enabled. Please enable the tokens for gasless swapping.',
      pleaseEnterAmountToSwap: 'Please enter amount to swap',
      cantSwapThesePair: `Can't swap these pair.`,
      equivalentAmountTo: `'s equivalent amount to `,
      isNotReceived: ' is not received.',
      youDontHaveEnough: "You don't have enough ",
      toPerformTransaction: ' to perform transaction',
      youHaveToPay: 'You have to pay ',
      areYouWillingToGiveApproval:
        ' as transaction fee for approval. Are you willing to give approval?',
      approvalSuccess: 'Approval Success',
      approvalFailed: 'Approval Failed',
      pleaseWaitForBlockchainConfirmation:
        'Please wait for blockchain confirmation',
      pleaseEnableYourAssetsToProceed: 'Please enable your assets to proceed',
      minimumSwapAmount: 'Minimum Swap Amount is: ',
      maximumSwapAmount: 'Maximum Swap Amount is: ',
      unableToSwap: 'Unable to swap',
      pleaseEnableTheAsset: 'Please enable the asset',
      enterValidSubject: 'Enter valid subject',
      enterValidMessage: 'Enter valid message',
      enterValidCategory: 'Select Category',
      enterValidWalletAddress: 'Enter valid wallet address',
      enterValidEthWalletAddress: 'Enter valid ETH wallet address',
      enterValidTxnLink: 'Enter valid transaction link',
      requestSubmitted: 'Request submitted successfully',
      doYouWantToDeleteS: 'Do you want to delete the screenshot?',
      invalidMnemonics: 'Invalid Mnemonics!',
      enterValidContactNameFormat: "You can't enter only number in contact name",
      enterValidWallettNameFormat: "You can't enter only number in wallet name",
      crossChainSupport: "CrossChain doesn't support on maker wallet"
    },
    notifications: {
      notifications: 'Notifications',
      announcements: 'Announcements',
      nolistfound: 'No list found',
    },
    merchantCard: {
      doc: 'Document',
      comboCardAmt: 'Combo card amount',
      pleasePayTheUpgradeFee:
        'Please pay the upgrade fee, and after payment is successful, the level will be upgraded.',
      progress: 'In progress',
      Success: 'Success',
      Failed: 'Failed',
      Consume: 'Consume',
      Recharge: 'Recharge',
      Withdrawal: 'Withdrawal',
      TransferIn: 'Transfer (In)',
      Transfer: 'Transfer',
      Other: 'Other',
      SettlementAdjustment: 'Settlement Adjustment',
      Refund: 'Refund',
      Paymentreversal: 'Payment reversal',
      Fee: 'Fee',
      Feereversal: 'Fee reversal',
      OTCrefund: 'OTC refund',
      OTCrefundreversal: 'OTC refund reversal',
      Creditreconciliation: 'Credit card bill reconciliation',
      PurchaseCoin: 'Purchase Crypto Coin',
      CancelCard: 'Cancel Card',
      Applied: 'Applied',
      rejected: 'Rejected',
      activated: 'Activated',
      cardDetail: 'Card Detail',
      selectGender: 'Select Gender',
      zip_code: 'Zip Code',
      state: 'State',
      proceed: 'Proceed',
      prepaidCard: 'Prepaid Card',
      virtualCard: 'Virtual Card',
      usPrefferedCard: 'US Preferred Card',
      unableToLoadCard:
        'Unable to load card details. Pull down to refresh or try again later.',
      apply: 'Apply',
      itTakesTimeConfirmPayment:
        'It takes time to confirm payment. Please ignore if fee is already paid.',
      cardFeatures: 'Card Features',
      payFee: 'Pay Fee',
      cardBalance: 'Card Balance',
      deposit: 'Deposit',
      trade: 'Trade',
      history: 'History',
      noTransactionHistoryFound: 'No Transaction History Found',
      applicationSubmitted: 'Application Submitted!',
      awaitingpaymentconfirmation: 'Awaiting payment confirmation.',
      cardCurrency: 'Card Currency',
      approxCardIssuingfee: 'Approx. card issuing fee',
      USDTTRX: 'USDT(TRX)',
      consumptionMethod: 'Consumption method',
      crypto: 'Crypto',
      depositFeeRate: 'Deposit fee rate',
      transaction: 'Transaction',
      easyAndQuickApplicationProcess: 'Easy and quick application process',
      uniquewalletAddressesTohaveSecuredPayments:
        'Unique wallet addresses to have secured payments',
      instantActivationforVirtualCards: 'Instant activation for Virtual Cards',
      earnrewardsbymakingreferrals: 'Earn rewards by making referrals',
      USD: 'USD',
      verify: 'verify',
      verified: 'verified',
      currency: 'Currency',
      type: 'Type',
      code: 'Code',
      submit: 'Submit',
      amountToBePaid: 'Amount to be paid',
      USDT: 'USDT',
      pleasePayTheAccountOpeningFee:
        'Please pay the account opening fee, and' +
        `${'\n'}` +
        'after payment is successful, the virtual' +
        `${'\n'}` +
        'card will be active immediately',
      issuingFee: 'Issuing fee',
      paymentCurrency: 'Payment currency',
      estimatedPaymentAmount: 'Estimated payment amount',
      walletAddress: 'Wallet Address',
      applyforTriskelCard: 'Apply for Triskel Card',
      applyforUsCard: 'Apply for Premium Card (Black)',
      applicationInformation: 'Application' + `${'\n'}` + 'information',
      fee: 'Fee',
      chooseCurrency: 'Choose Currency',
      done: 'Done',
      applicationSuccessful: 'Application Successful',
      oncePaymetConfirmes:
        'Once the fee payment is confirmed, you will see the card issued with your details.',
      DoorStepDelivery: 'Door-step delivery for physical cards',
      applicationApplied: 'Application Applied!',
      linkYourCard: 'Link Your Card',
      activateYourCard: 'Activate Your Card',
      informationInReview: 'Information In Review',
      youCanResubmitKycverificationInformation:
        'You can Re-submit for KYC verification information',
      reApplyKYC: 'Re-Apply KYC',
      submitKYC: 'Submit KYC',
      kycIsRejected: 'KYC is Rejected!',
      kycInreviewProcessTime: 'KYC is in review, process time 24-48 hours.',
      ViewCardDetails:
        'To view the details of the card, please enter 6 digit pin code send on your mail.\n',
      takesTimeToconfirmPayment:
        'It takes time to confirm payment. Please ignore if fee is already paid.',
      rechargeCardViaTriskal: `Recharge Card via Triskel Capital Wallet\n\nCard Address to recharge `,
      is: 'is: ',
      publicAddress: 'Public Address',
      forUSDTTRCdepositonly: 'For USDT (TRC 20) deposit only',
      note: 'Note:',
      minimumDepositvalueis: 'Minimum Deposit value is:',
      calculateYourTopUp: 'Calculate Your Top Up',
      clickonButtontoGetCal:
        'Click on the button to get the calculations for the top up value for the card.',
      transactionHistory: 'Transaction History',
      pleaseUploadThePassportInformationPageWithOnAvatar:
        'Please upload the passport information page with on avatar',
      ensureIDframeCompleteFontClearBrightnessUniform:
        'Ensure that the ID frame is complete,the font is clear,and the brightness  is uniform',
      photoShouldBeLessThenSupportJpgJpegPng:
        'The photo should be less then 2M,support jpg/jpeg/png',
      pleaseUploadTheSelfieWithHoldingIDcard:
        'Please upload the selfie with holding ID card',
      pleaseUploadTheSignature:
        'Please upload the signature with proper visibility',
      takeSelfieWithHandHoldingPassportInformationPageWithAvater:
        'Take a selfie with hand holding passport information page with an avater',
      save: 'Save',
      reset: 'Reset',
      confirm: 'Confirm',
      reviewInformation: `Review${'\n'}Information`,
      noFeeIsChargedForTheCardLinkingServices:
        'No fee is charged for the card linking service, and it cannot be changed after the linking is successful.',
      theMailerNumberUniqueAndRelevent:
        'The mailer number is unique and relevant. After receiving the mail, check all the relevant information, and do not disclose the card number and mailer number to anyone.',
      userNotAbletoUnlink:
        'Once linked, user will not be able to Unlink the added card.',
      cardLinkingInstruction: 'Card linking instruction:',
      triskelPhysicalCardLinkingService:
        'Triskel Physical Card Linking Service',
      whatIsTheLinkingYourCardService: 'What is the linking your card service?',
      cardLinkingServiceIsLaunched:
        'Card linking service is launched for Triskel physical users to link the account number submitted with the KYC is required to be completed. Once succeeded, User should be able to top-up card with enabled fiat currencies.',
      issued: 'Issued',
      virtualVersionAppearHere: `Once you have Linked your${'\n'}physical card, Virtual version will${'\n'}appear here`,
      valid: 'Valid',
      THRU: 'THRU',
      male: 'Male',
      female: 'Female',
      resend: 'Resend',
      pleaseFillInTheCorrectDetails:
        'Please fill in the correct details. Card will be shipped to the given address',
      physicalCard: 'Physical Card',
      gender: 'Gender',
      country: 'Country',
      province: 'Province',
      city: 'City',
      postcode: 'Postcode',
      countryCode: 'Country Code',
      number: 'Number',
      SMSCode: 'SMS Code',
      emailCode: 'Email Code',
      ApplicationInformation: `Application${'\n'}information`,
      chooseGender: 'Choose Gender',
      scanQRcode: 'Scan a QR code',
      premBlack: 'Premium Card (Black)',
      metallicBlack: 'Virtual Card (Metallic)',
    },
    placeholderAndLabels: {
      camera: 'Camera',
      gallery: 'Gallery',
      address: 'Address',
      firstName: 'First Name',
      enterFirstnamehere: 'Enter first name here',
      lastName: 'Last Name',
      enterLastnamehere: 'Enter Last name here',
      phoneNumber: 'Phone Number',
      EnterNumberhere: 'Enter Number here',
      enterOTP: 'Enter OTP',
      enterCheckCode: "Enter Checker's Code",
      entercode: 'Enter code',
      enterCode: 'Enter Code',
      email: 'Email',
      enterEmail: 'Enter Email',
      pasteWalletaddress: 'Paste wallet address',
      searchuser: 'Search user',
      enterWalletName: 'Enter Wallet Name',
      enterWalletNameHere: 'Enter wallet name here',
      enterNamehere: 'Enter name here',
      enterEmailhere: 'Enter email here',
      enterSubjectHere: 'Enter subject here',
      enterMessageHere: 'Enter message here',
      enterWalletAdd: 'Enter Wallet Address',
      enterWalletHere: 'Enter wallet address here',
      enterTxnLink: 'Enter transaction link here',
      select: 'Select',
      selectNetwork: 'Select Network',
      selectDOB: 'Select DOB',
      dateOfBirth: 'Date of birth',
      selectNationality: 'Select nationality',
      nationality: 'Nationality',
      documentType: 'Document type',
      passport: 'Passport',
      documentNo: 'Document no',
      enterDocumentNo: 'Enter document no.',
      documentExpiry: 'Doc Expiry Date',
      enterDocumentExpiry: 'Doc Expiry Date',
      frontIDphoto: 'Front ID photo',
      Upload: 'Upload',
      SignatureMandatory: 'Signature is mandatory',
      SelfieOfHandHoldingIDcard: `Selfie of hand holding \n ID card`,
      Signature: 'Signature',
      emergencyContact: 'Emergency contact',
      pleaseEntertheName: 'Please enter ' + 'the name',
      emergencyNumber: 'Emergency number',
      pleaseEnterNumber: 'Please enter ' + 'number',
      informationInReview: 'Information In Review',
      chooseDocumentType: 'Choose Document Type',
      userKYC: 'User KYC',
      paste: 'Paste',
      tokenName: 'Token Name',
      enterYourWalletName: 'Enter your wallet name',
      enterAmount: 'Enter amount',
      convertedAmount: 'Converted amount',
      envelopeNumber: 'Envelope Number',
      pleaseEnterTheEnvelopeNumber: 'Please enter the envelope number',
      linkingName: 'Linking Name',
      pleaseEnterYourName: 'Please enter your name',
      linkCardNumber: 'Link Card Number',
      pleaseEnterTheCardNumber: 'Please enter the card number',
      enterProvince: 'Enter Province',
      enterCity: 'Enter City',
      enterStreet: 'Enter Street',
      streetAddress: 'Street Address',
      enterPostcode: 'Enter Postcode',
      enterCode: 'Enter Code',
      sendCode: 'Send Code',
      searchWatchlist: 'Search watchlist',
    },
    sendTrx: {
      walletAddress: 'Wallet Address',
      Amount: 'Amount',
      enterAmount: 'Enter Amount',
      max: 'MAX',
      Balance: 'Balance :',
      transactionFee: 'Transaction Fee',
      SEND: 'Send',
      SUBMIT: 'SUBMIT',
      Cancel: 'Cancel',
      paste: 'Paste',
      rechargeAmountshouldgreaterthanequal:
        'Recharge Amount should be greater than or equal to',
      transactions: 'Transactions',
      transact: 'Transact',
      paymeViaTriskelCapitalWallet: 'Pay me via Triskel Capital Wallet',
      myPublicAddressToReceive: `\n\nMy Public address to receive `,
      slow: 'Slow',
      Average: 'Average',
      Fast: 'Fast',
      my: 'My ',
      adress: ' address: ',
      SHARE: 'SHARE',
      networkFees: 'Network Fees',
      providerFees: 'Provider Fees',
      Quote: 'Quote',
      slippage: 'Slippage',
      transactionFees: 'Transaction Fees:'

    },
    addressBook: {
      addressBook: 'Address Book',
      searchTxt: 'Search Address',
      searchByName: "Search by name",
      saved: 'Saved',
      addNewContact: 'Add New Contact',
      addNewAddress: 'Add New Address',
      nameYourContact: 'Name your contact',
      addWalletAddress: 'Add Wallet Address',
      addWalletName: 'Add Wallet name',
      network: 'Network',
      saveContact: 'Save Contact',
      addCustomToken: 'Add Custom Token',
      buySellCrypto: 'Buy/Sell Crypto',
      contractAddress: 'Contract Address',
      name: 'Token name',
      nameSimple: 'Name',
      enterName: 'Enter Token name',
      symbol: 'Symbol',
      decimals: 'Decimals',
      yes: 'Yes',
      disclaimer: "Anyone can create a token, including fake versions of existing tokens, Learn about scams and security risks."
    },
    alchemy: {
      alchemy: 'Alchemy',
      currency: 'Currency',
      currencyUpdated: 'Currency updated',
    },
    receive: {
      address: 'Address',
      sendOnlySmartChain: 'Send only smart chain',
      shareYourAddress: 'Share Your Address',
      setAmount: 'Set Amount',
      permanentLossOfFunds:
        'to this address. Remember, If you send the wrong type of digital asset that will result in permanent loss of funds.',
    },
    buySell: {
      payment: 'Payment',
      proceedToBuy: 'Proceed to Buy',
      buy: 'Buy',
      selectCountry: 'Select Country',
      bestPrice: '(Best Price)',
      exchangePairIsNotSupported: 'Exchange Pair is not supported',
      proceedToSell: 'Proceed to Sell',
      platformFeeTooHigh: 'Platform fee too high',
      sell: 'Sell',
      transak: 'Transak',
      Range: 'Range:',
      addAssetsTOWatchlist: 'Add Assets to the Watchlist'
    },
    checkOut: {
      Checkout: 'Checkout',
      quantityYouReceiveMayDeviate:
        'Due to market volatility, the quantity you receive may deviate slightly from your order.',
      paymentGateway: 'Payment Gateway',
      networkFee: 'Network Fee',
      platformFee: 'Platform Fee',
      totalAmount: 'Total Amount',
      paymentGatewayToCompleteThePurchase:
        'Confirm to enter a secure payment gateway to complete the purchase',
      confirmPurchase: 'Confirm Purchase',
      per: 'PER',
    },
    pins: {
      enterCode: 'Enter Code',
      createSecretCode: 'Create Secret Code',
      secretCodeNew: 'Create Secret Code',
      confirmSecretCode: 'Confirm Code',
      confirmSecretCode1: 'Confirm Secret Code',
      confirmCode: 'Confirm Code',
      pleaseReenterYourCode: 'Please re-enter your 6 digit Code',
      Continue: 'Continue',
      continueSwap: 'Continue Swap',
      restoreWallet: 'Restore Wallet',
      yourWalletAccessIsRestored: 'Your wallet access is restored',
      yourWalletisCreated: 'Your wallet is created.',
      enableBiometrics: 'Enable Biometrics',
      biometricsEnabled: 'Biometrics Enabled',
      enableFaceId: 'Enable FaceId',
      faceIdEnabled: 'FaceId Enabled',
      pleaseConfirmYourPIN: 'Please confirm your 6-digit PIN',
      secretCode: 'Secret Code',
      pleaseEnterNewDigitCode: 'Please enter a new 6 digit Code',
      please: 'Please',
      yourDigitCode: ' your 6 digit Code',
      Weak: 'Weak',
      strong: 'Strong',
      newSecretCode: 'New Secret Code',
      pleaseEnterNewDigitPIN: 'Please enter a new 6-digit PIN',
      enterYourDigitCode: 'enter your 6 digit Code',
      forgotPIN: 'Forgot PIN?',
      loginToTriskelWallet: `Login To\nTriskel Wallet`,
      youNeedToEnterTheEmailToAccessTheAccount:
        'You need to enter the email to access the account',
      confirmOldSecretCode: 'Confirm Old Secret Code',
      pleaseEnterYourDigitCode: 'Please enter your 6 digit Code',
      resetPIN: 'Reset PIN',
      resetCode: 'Reset Code',
      biometricFaceID: 'Biometric/Face ID',
      biometric: "Biometric"
    },
    createWalletTexts: {
      pleaseEnterName: 'Please enter name',
      EnterValiName: 'Enter valid name',
      validName:
        'Wallet name must include minimum 3 characters and maximum 20 characters',
      nameOfYourWallet: 'Name of your wallet',
      walletRestored: 'Wallet Restored',
      namingYourWallet:
        'Naming your wallet will help you keep track of multiple wallets, easily.',
      enterName: 'Enter Name',
      maxLimit: 'Max Limit:',
    },
    priceAlert: {
      createPriceAlert: ' Create Price Alert',
      currentPrice: 'Current Price :',
      alertType: 'Alert Type',
      priceRisesTo: 'Price Rises To',
      priceDropsTo: 'Price Drops To',
      addPrice: 'Add Price',
      priceAlertCreated: 'Price Alert Created!',
      notificationWillSent: 'You will receive a notification as soon as the coin reaches the price set by you.',
      noData: 'No data',
      priceAlert: 'Price Alert',
    },
    browser: {
      Bnb: 'Bsc',
      Ethereum: 'Ethereum',
      Matic: 'Matic',
      confirmTransaction: 'Confirm Transaction',
      to: 'To',
      From: 'From',
      gasFee: 'Gas Fee',
      total: 'Total',
      Dapp: 'Dapp',
      noListFound: 'No List Found',
    },
    deposit: {
      selectCurrencyToCalculateTopup: 'Select currency to calculate top-up',
      howMuchBalanceWouldYouLike:
        'How much balance would you like to load in your Triskel Wallet?',
      youNeedToDeposit: 'You need to deposit',
      instructions: 'Instructions',
      depositWalletAddress: 'Deposit Wallet Address',
      calIsAproxxValue: `This above shown calculation is an approx. value.\nThe transaction will be executed at market value.`,
      theDepositIntoTheCard:
        'The deposit into the card may take up to 24 hours.',
    },
    detailTrx: {
      applyFilters: ' Apply filters',
      Coin: 'Coin',
      Status: 'Status',
      typeOfTransaction: 'Type of Transaction',
      dateRange: 'Date Range',
      all: 'All',
      completed: 'Completed',
      pending: 'Pending',
      Failed: 'Failed',
      Deposit: 'Deposit',
      Withdraw: 'Withdraw',
      swap: 'Swap',
      cardFee: 'Card Fees',
      cardRecharge: 'Card Recharge',
      Buy: 'Buy',
      Sell: 'Sell',
      smartContractInteraction: 'Smart Contract Interaction',
      confirmed: 'confirmed',
      dapp: 'dapp',
      transactionDetails: 'Transaction Details',
      crossChainSwap: 'Cross-chain Swap',
      smartContractExecution: 'Smart Contract Execution',
      contractExcecutedSuccessfully: 'Contract excecuted successfully.',
      addAssetsTOWatchlist: 'Add Assets to the Watchlist'
    },
    manage: {
      updateList: 'Update',
      manage: 'Manage Token',
      Update: 'Add Custom Token',
      manageAccount: 'Manage Account',
      defaultAccount: 'Default Account',
      addAccountUsing: '---- Add Account Using ----',
      logout:
        'You will be logged out after deleting the account, Do you want to continue?',
    },
    portfolio: {
      Portfolio: 'Portfolio',
      walletStats: 'Wallet Stats',
      watchlist: 'Watchlist',
      addWatchlist: 'Add to Watchlist',
      addTokens: "Add Tokens"
    },
    referral: {
      toUpgrade: 'To be able to Upgrade your level from ',
      to: ' to ',
      youmust: ' you must:',
      refs: 'Referrals',
      more: 'more to go',
      havingARef: 'Having a Referral Code?',
      getReward: 'Get a reward by using my referral code: ',
      plsDownload: 'Please download App by using below link:',
      signSave: 'Signature saved!',
      adminApprove:
        'Your request has been submitted successfully. Please wait for admin approval',
      merchantLevelApprove: 'You successfully upgraded to Master Franchisee',
      adminReject:
        'Your request has been declined by admin. Please resubmit your request',
      levelUpgrade: 'Level Upgrade',
      alreadyAvailed: 'Referral Code already availed for this device',
      addSuccess: 'Referral code added successfully!',
      noHistory: 'No Referral History Found',
      claimRef: 'Claim',
      referralnRewards: 'Referral & Rewards',
      buyPrepaidCards: 'Buy Prepaid Cards',
      currentLevel: 'Current Level',
      signContract: 'Sign the contract',
      level: 'Level of user',
      getStarted: 'Get Started',
      refLink: 'Referral Link',
      upgrade: 'Upgrade',
      noRefer: 'No. of Referrals',
      buyComboCards: 'Buy Combo Cards',
      step: 'Step',
      referralRoadMap: 'How to Upgrade?',
      generalPublic: 'General Public',
      walletUser: 'Need to be a Triskel member',
      buyCards: 'Buy 100 combo cards',
      franchisee: 'Franchisee',
      referrer6Months: '600+ referrer in 6 months',
      premFranchisee: 'Premium Franchisee',
      buy250Cards: '5000+ card in lifetime+ buy 250 cards',
      masterFranchisee: 'Master Franchisee',
      sent: 'Sent',
      receive: 'Receive',
      received: 'Received',
      invitingYou:
        "I am inviting you to use Triskel Wallet, a simple and secure wallet. Here's my referral link",
      useThisCode: ' Use this code to earn rewards.',
      referralRewards: 'Referral Rewards',
      referEarn: 'Refer & Earn',
      earnUptoINRRewards: 'Up to 1% of all your referrals card top ups.',
      share: 'Share',
      TodayTotal: `Today's Total`,
      claimsDistribution: 'Claims Distribution',
      totalRewards: 'Total Rewards',
      rewardsHistory: 'Rewards History',
      security: 'Security',
      Biometric: 'Biometric',
      startEarning: 'Once we activate the cards , you start earning!',
    },
    setting: {
      themeUpdateSuccess: 'Theme updated successfully',
      lightTheme: 'Light Theme',
      darkTheme: 'Dark Theme',
      theme: 'Theme',
      settings: 'Settings',
      manageAccount: 'Manage Account',
      triskelCards: 'Triskel Cards',
      security: 'Security',
      currencyPreference: 'Currency Preference',
      priceAlert: 'Price Alert',
      addressBook: 'Address Book',
      aboutUs: 'About Us',
      privacyPolicy: 'Privacy Policy',
      contactUS: 'Contact Us',
      logout: 'Logout',
      yes: 'Yes',
      help: 'Help & Support',
      language: 'Language',
      english: 'English',
      spanish: 'Spanish',
      LanUpdateSuccess: 'Language updated successfully',
      preferences: 'Preference',
      referalAndRewards: 'Referral & Rewards',
      nativeCurrency: 'Native Currency',
      addressBook: 'Address Book',
      contactUs: 'Contact Us',
      aboutUs: 'About Us',
      walletConnect: 'Wallet Connect',
      privacyPolicy: 'Privacy Policy',
      prepaidCards: 'Prepaid Cards',
      facebook: 'Facebook',
      instagram: 'Instagram',
      telegran: 'Telegram',
      default: "Default",
      backupMnemonics: "Backup Mnemonics",
      backupPrivateKey: "Backup Private Key",
      deleteWallet: "Delete Wallet",
      defaultWallet: "Default Wallet",

    },
    walletConnection: {
      noConnection: "Connect your wallet & manage existing connections.",
      addNewConnection: "Add New Connection",
      newConnection: "New Connection",
      scanQR: "Scan QR to Connect Wallet",
      connectDApp: "Connect DApp",
      walletConnect: "Wallet Connect",
      connect: "Connect",
      disconnect: "Disconnect",
      manageExistingConnections: "Connect your wallet & manage existing connections."

    },
    swapText: {
      swap: 'Swap',
      crossChain: 'Cross Chain',
      onChain: 'On Chain',
      pairNotSupported: 'Pair not supported for now',
      approval: 'Approval',
      approve: 'Approve',
      convertedAmountIsLesserThanRelayerFee:
        '*Converted amount is lesser than relayer fee. Try with a bigger value.',
      estimatedRate: 'Estimated Rate',
      estimatedTime: 'Estimated Time',
      serviceFee: 'Service Fee',
      swapFeeTokenTransferFee: 'Fee = Swap Fee + Token Transfer Fee',
      relayerServiceFee: 'Relayer Service Fee',
      youWillReceive: 'You will receive',
      chain: 'Chain',
      from: "From",
      contactAddress: "Contact Address",
      provider: "Provider",
      providers: "Providers",
      maxSlippage: "Max Slippage",
      networkfess: "Network Fees",
      myWallet: "My Wallet",
      myWallets: "My Wallets",
      continueSwap: "Continue Swap",
      previewSwap: "Preview Swap",
      trasactionSetting: "Transaction Settings",
    },
    commonText: {
      yesIUnderstand: 'Yes, I Understand',
      tryPin: "Records not found using biometrics. Please try again with your PIN.",
      sInfoNotRecognized: "Biometric recognition failed. Please try again.",
      sInfoSuccess: "Biometric recognized successfully.",
      sInfoCancelled: "Authentication was cancelled.",
      sInfoHeader: "Save PIN",
      sInfoDesc: "Save your PIN with biometrics to enable transaction processing through biometric authentication.",
      sInfoPermission: "We need your permission to retrieve PIN.",
      sInfoGetHeader: "Confirm Biometric",
      sInfoGetDesc: "Confirm biometric to access PIN.",
      successful: 'Successful',
      paymentDoneRequestForApproval:
        'Payment is done. Request sent for approval.',
      addresses: ' Addresses',
      assets: 'Assets',
      allocation: 'Allocation',
      from: 'From ',
      to: 'To',
      GasPrice: 'Gas Price',
      GasLimit: 'Gas Limit',
      Nonce: 'Nonce',
      Value: 'Value',
      TransactionFee: 'Transaction Fee',
      Slow: 'Slow',
      Average: 'Average',
      Fast: 'Fast',
      Confirm: 'Send',
      CANCEL: 'CANCEL',
      applicationSubmitted: 'Application Submitted!',
      ChooseAction: 'Choose Action',
      Verify: 'Verify',
      Swap: 'Swap',
      ReviewTransaction: 'Review Transaction',
      Provider: 'Provider',
      methodBeingCarriedOutForTheTransaction:
        'This is the method being carried out for the transaction.',
      onChainSwap: '1Inch Swap',
      networkFee: 'Network Fee',
      blockchainNetworkChargesBlockchain:
        'The blockchain network charges a blockchain fee based on blockchain usage.',
      myWallet: 'My wallet ',
      CrossChainSwap: 'Cross-Chain Swap',
      Send: 'Confirm',
      Asset: 'Asset',
      MaxTotal: 'Max Total',
      Congratulations: 'Congratulations!',
      walletCreatedSuccessfully: 'Wallet Created Successfully',
      ChooseNetwork: 'Choose Network',
      Select: 'Select',
      Approve: 'Approve',
      Transfer: 'Transfer',
      PaymentGateway: 'Payment Gateway',
      Transak: 'Transak',
      Alchemy: 'Alchemy',
      Range: 'Range',
      Loading: 'Loading...',
      ChooseAsset: 'Choose Asset',
      Search: 'Search',
      NoListFound: 'No list found',
      ChooseCountryCode: 'Choose Country Code',
      ChooseCountry: 'Choose Country',
      ConfirmSwap: 'Confirm Swap',
      ReferralCode: 'Referral Code',
      YouNeedToEnterTheReferralCode:
        'You need to enter the referral code to earn the rewards',
      EnterReferralCode: 'Enter referral code',
      SKIP: 'SKIP',
      Balance: 'Balance',
      SessionTimeout: ' Session Timeout',
      SelectSessionTimeout: 'Select Session Timeout',
      SmartContractExecution: 'Smart Contract Execution',
      TokenId: 'Token Id -',
      ContractExcecutedSuccessfully: ' Contract executed successfully.',
      seconds: 'Seconds',
      immediately: 'Immediately',
      minutes: 'Minutes',
      minute: 'Minute',
    },
    contactUs: {
      cardRelated: 'Card Related',
      GetInTouch: 'Get in touch',
      supportText:
        'This is official Triskel support channel please fill all the fields and provide links when applicable, we will contact you shortly through emails',
      name: 'Name',
      email: 'E-mail',
      subject: 'Subject',
      message: 'Message',
      category: 'Category',
      walletAddress: 'Wallet Address',
      txnLink: 'Transaction Links',
      attachScreenshot: 'Attach screenshots',
      cancel: 'Cancel',
      send: 'Send',
      screenshot: 'Screenshots',
      buySell: 'Buy/Sell',
      sendReceive: 'Send/Receive',
      swap: 'Swap',
      // virtualPhysical: 'Virtual Card/Physical Card',
      virtualPhysical: 'Virtual Card',
      accountRelated: 'Account Related',
    },
    help: {
      supportTicket: 'Support Ticket',
      supportHistory: 'Support History',
      noListFound: 'No list found',
      ticketId: 'Ticket Id',
      subject: 'Subject',
      message: 'Message',
      lastUpdated: 'Last Updated',
      createdAt: 'Created At',
      remarks: 'Remarks',
      status: 'Status',
      open: 'Open',
      progress: 'In Progress',
      resolved: 'Resolved',
    },
    aggreement: {
      and: ' and',
      agreement: 'REFERRAL AGREEMENT',
      agreText: `IMPORTANT! PLEASE READ THIS DOCUMENT CAREFULLY. THIS DOCUMENT SHALL BECOME LEGALLY BINDING UPON YOURSELF AFTER MARKING “ACCEPT TERMS AND CONDITIONS OF THE REFERRAL AGREEMENT” `,
      agreText22: 'CHECKBOX ',
      agreText23: `. IF THERE IS ANYTHING IN THIS DOCUMENT THAT YOU DO NOT UNDERSTAND OR IN CASE OF ANY CLARIFICATION OR INTERPRETATION REGARDING THE PRESENT REFERRAL AGREEMENT, PLEASE CONTACT US BEFORE ACCEPTING THE TERMS AND CONDITIONS.`,
      agreText1: `This document (hereinafter referred to as the Referral agreement) constitutes conditions for the membership process that is done by the General Public, Franchisee, Premium Franchisee or/and Master Franchisee (hereinafter referred to as “Members”) and `,
      agreText21: ` (hereinafter referred to as “Triskel Capital”. In addition to this agreement, relationships with the Members and The Triskel App will be governed by the User Agreement and Privacy Policy which are currently in force and are always available on the Website at`,
      termsLink: 'https://triskelcap.com/termsofuse',
      privacyLink: 'https://triskelcap.com/privacy-policy',
      agreText4: `and mandatory statutes and other Governing Laws and Legal Act of the United States. In the event of any inconsistency between the Referral Agreement Terms and the User Agreement Terms, the Referral Agreement shall prevail.\n\nTriskel Capital enables users to store, exchange or transmit fiat and/or digital currency to designated recipients located in specific jurisdictions for a specified purpose, over the internet. Triskel Capital provides its members with a non-custodial digital currency wallet.\n\nBy way of the present Referral Agreement, Triskel Capital is providing a Referral Program by which any General Public who are desirous of availing the Referral Program shall be governed by the conditions stipulated and each party shall remain responsible for the performance of such duties.`,
      agreText2:
        'NOW, THEREFORE, IN CONSIDERATION OF THE MUTUAL COVENANTS, GENERAL TERMS AND REFERRAL AGREEMENT CONDITIONS, THE PARTIES WITH THE INTENT TO BE LEGALLY BOUND HEREBY AGREE AS FOLLOWS:',
      agreText3: '1.   DEFINITIONS AND INTERPRETATION',
      def: 'Definitions.',
      defContent:
        ' In this Agreement unless there is something in the context inconsistent therewith, the following terms shall have the following meanings:',
      agree: '(a) “Agreement”',
      agreeContent:
        ' shall mean this Referral Agreement and all appendices, annexes or exhibits thereto.',
      combo: '(b) “Combo Card”',
      comboContent:
        ' shall mean and include combination of a physical card and a digital card',
      Commission: '(c) “Commission”',
      CommissionContent: 'as stipulated in Clause 3.1 read with Schedule-I',
      digiCard: '(d) “Digital Card”',
      digiCardContent:
        ' A virtual card that is not physical and can be purchased by itself on the Triskel App',
      genPub: '(e) “General Public”',
      genPubContent:
        ' means any person who has downloaded the application of Triskel Capital.',
      physCard: '(f) “Physical Card”',
      physCardContent:
        ' A card that is tangible and physical and can only be acquired if the digital card has been obtained first.',
      agreText5: '\n2.  SCOPE',
      scope: `2.1. Triskel Capital in accordance with the terms and conditions agrees on non-exclusive basis to refer and introduce the General Public to 4 levels of Memberships as a part of Referral Agreement.\n\n2.2. This Agreement expressly contains all the duties of the Members and Triskel Capital and only between them. No implied duties or obligations shall be read or deemed to be read into this Agreement against Triskel Capital and its Members. Apart from this Agreement, Triskel Capital and Members shall not be bound by the provisions of any agreement, arrangement or understanding between Triskel Capital and Members except for the User Agreement and Privacy Policy which are currently in force.\n\n2.3. The 3 levels of Memberships which the present Referral Agreement offers to General Public are:\n\na) Franchisee\nb) Premium Franchisee\nc) Master Franchisee\n\n2.4 Any prospective member of the General Public who downloads the application and subsequently contacts Triskel Capital and signs the present Referral Agreement in addition to purchase of 100 combo cards will become a “Franchisee”. Franchisee can refer only to General Public\n\n2.5 Any Franchisee who has sold 600 combo cards in the first 6 months can apply to become a  “Premium Franchisee“ by contacting Triskel Capital and signing the present Referral Agreement. A Premium Franchisee can refer to a Franchisee as well as the General Public\n\n2.6. Any Premium Franchisee who has sold 5000 combo cards or more in any period and is desirous of becoming a Master Franchisee has to purchase 250 cards and consequently attain the membership as “Master Franchisee” in the same manner as provided above by contacting Triskel Capital and signing the present Referral Agreement. A Master Franchisee can refer to a Premium Franchisee, a Franchisee as well a General Public.
\n2.7. Members understand and agree that they are entitled to Commission in hierarchical following manner: -
\na) The General Public will earn from the General Public by way of direct referral.
\nb) When a direct General Public of a Franchisee becomes a Franchisee, which means that a Franchisee has a direct Franchisee under its organisation, then Franchisee will be entitled to Commission from total volume acquired by the new Franchisee. It is further agreed that The Franchisee can earn from the total volume of another Franchisee and its General Public.
\nc) When a direct Franchisee of a Premium Franchisee becomes a Premium Franchisee, which means that a Premium Franchisee has a direct Premium Franchisee under its organisation, the Premium Franchisee will be entitled to commissions from total volume acquired by the new Premium Franchisee. It is further agreed that Premium Franchisee can earn from the total volume of another Premium Franchisee, a Franchisee and General Public.
\nd) When a direct Premium Franchisee of a Master Franchisee becomes a Master Franchisee which means that a Master Franchisee has a direct Master Franchisee under its organisation the Master Franchisee as you can see in the table of commissions will be entitled to commissions from total volume acquired by the new Master Franchisee. It is further agreed that Master Franchisee can earn from the total volume of another Master Franchisee, a Premium Franchisee, a Franchisee and General Public.
\n2.8. Members understand and agree that every time a membership is upgraded next level then a new user ID shall be created.`,
      consideration: '\n3.  CONSIDERATION AND COMMISSIONS',
      considerationText: `3.1. In consideration for each entitled Member, Members are entitled to earn commissions from each referral made by a Member. Members are entitled to the percentage of the commission as stipulated in the Schedule-I of the present Referral agreement.
      \n3.2. Parties agree and accept that Commissions generated by the General Public will be deposited to their respective physical card only. It is clarified that in case that the commission that needs to be paid is less than the minimum amount allowed for recharging the card, the amount will be kept by Triskel Wallet Company until the amount is equal or greater than the minimum for a single deposit.
      \n3.3. It is specified that Parties agree and accept that 30% of the Commissions generated by the Franchisee, Premium Franchisee or Master Franchisee will be deposited directly to their physical card and remaining 70% Commission will be deposited via crypto in their respective USDT TRON wallet.
      \n3.4. The Members understand and agree that Triskel Capital has every right to amend or change the terms and conditions, without any objection or intervention of the other party.`,
      relationShip: '\n4. RELATIONSHIP BETWEEN THE PARTIES',
      relationShipText: `The relationship between the Member and Triskel Capital is an independent contractual basis. Nothing contained herein shall be deemed to create any association, partnership, joint venture, or relationship of principal and agent or master and servant, or employer and employee between the Parties hereto or any affliates or subsidiaries thereof or to provide either Party with the right, power or authority, whether express or implied to create any such duty or obligation on behalf of the other Party.`,
      duration: '\n5. DURATION.',
      durationText: `5.1. This Agreement shall be in force from the Effective Date and shall remain in force for an unlimited period, or until Triskel Capital decides to end its Referral program.
\n5.2. Triskel Capital undertakes to give 5 working days prior written notice to Member when it decides to end its Referral program
\n5.3. Members understand and agree that when Triskel Capital decides to end its Referral program then Triskel shall grant 5 working days for withdrawal of Commissions/funds to all its members and general public.`,
      assignment: '\n6. ASSIGNMENT',
      assignmentText: `Members under this Agreement may not assign or transfer any of rights or obligations hereunder, including by operation of law. Any attempted assignment in violation of this Agreement and shall be void.`,
      govtLaw: '\n7. GOVERNING LAW, SETTLEMENT OF DISPUTES, AND JURISDICTION.',
      govtLawText: `Any dispute relating to this Referral Agreement and any non-contractual obligations arising out of or in connection with it are governed by the laws of the Dubai, UAE. The Dubai International Arbitration Centre (DIAC) shall have exclusive jurisdiction to settle any dispute arising out of or in connection with this Agreement. Each of the Parties agrees that, if any dispute(s) or difference(s) shall arise between the Parties in connection with or arising out of this Agreement, the Parties shall attempt, for 30 (thirty)days from the receipt of a notice from the other Party of the existence of a dispute(s), to settle such dispute(s) by mutual discussions between the Parties. If the said dispute(s) cannot be settled by mutual discussions within the thirty days provided above, either Party may refer the matter to a sole neutral arbitrator to be mutually appointed and accepted by the parties`,
      // govtLawText: 'Any dispute relating to this Referral Agreement and any non-contractual obligations arising out of or in connection with it are governed by the laws of the United States of America. The courts in the United States have exclusive jurisdiction to settle any dispute arising out of or in connection with this Agreement. Each of the Parties agrees that, if any dispute(s) or difference(s) shall arise between the Parties in connection with or arising out of this Agreement, the Parties shall attempt, for 30 (thirty)days from the receipt of a notice from the other Party of the existence of a dispute(s), to settle such dispute(s) by mutual discussions between the Parties. If the said dispute(s) cannot be settled by mutual discussions within the thirty days provided above, either Party may refer the matter to a sole neutral arbitrator to be mutually appointed and accepted by the parties',
      severability: '\n8. SEVERABILITY.',
      severabilityText:
        'If any provision of this Agreement is determined by a court of competent jurisdiction to be invalid or unenforceable, then the remaining provisions of this Agreement will nevertheless be given full force and effect.',
      liability: '\n9. LIMITATION OF LIABILITY.',
      liabilityText: `EACH PARTY’S LIABILITY TO THE OTHER PARTY, INCLUDING ALL LIABILITIES ARISING OUT OF OR RELATED TO THIS AGREEMENT, FROM ANY CAUSE OR CAUSES, AND REGARDLESS OF THE LEGAL THEORY, INCLUDING BREACH OF CONTRACT, WARRANTY, NEGLIGENCE, STRICT LIABILITY, OR STATUTORY LIABILITY, FOR A CLAIM SHALL NOT EXCEED THE REFERRAL FEES PAID OR PAYABLE TO REFERRER UNDER THIS AGREEMENT.
UNDER NO CIRCUMSTANCE SHALL EITHER PARTY BE LIABLE TO THE OTHER PARTY FOR ANY SPECIAL, INDIRECT, INCIDENTAL, PUNITIVE, EXEMPLARY, OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR RELATED TO THIS AGREEMENT, HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY (INCLUDING NEGLIGENCE), EVEN IF IT HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.`,
      text:
        '\n\nThe upgrade from general public to Franchisee, Premium Franchisee and Master Franchisee will take place manually from Triskel ́s admin panel as discussed.',
      schedule: 'SCHEDULE-I',
      commissions: 'COMMISSIONS',
      comText1: ' Commission for General Public Membership',
      subtext1: `●  Percentage from direct General Public Total Funds - 0.20%
●  Percentage from direct Franchisee Total Funds - N/A
●  Percentage from direct Premium from Franchisee Total Funds - N/A
●  Percentage from direct direct Master Franchisee Total Funds - N/A
●  For each card combo (digital+physical) sold to direct members - 20 USD
●  For each Digital Card sold - 15 USD
●  For each Physical Card Sold - 5 USD`,
      comText2: ' Commission for Franchisee Membership',
      subtext2: `●  Percentage from direct General Public Total Funds - 0.50%
●  Percentage from direct Franchisee Total Funds - 0.10%
●  Percentage from direct Premium from Franchisee Total Funds - N/A
●  Percentage from direct direct Master Franchisee Total Funds - N/A
●  For each card combo (digital+physical) sold to direct members - 50 USD
●  For each Digital Card sold - 30 USD
●  For each Physical Card Sold - 20 USD`,
      comText3: ' Commission for Premium Franchisee Membership',
      subtext3: `●  Percentage from direct General Public Total Funds - 0.50%
●  Percentage from direct Franchisee Total Funds - 0.30%
●  Percentage from direct Premium from Franchisee Total Funds - 0.10%
●  Percentage from direct direct Master Franchisee Total Funds - N/A
●  For each card combo (digital+physical) sold to direct members - 50 USD
●  For each Digital Card sold - 30 USD
●  For each Physical Card Sold - 20 USD`,
      comText4: ' Commission for Master Franchisee Membership',
      subtext4: `●  Percentage from direct General Public Total Funds - 1.00%
●  Percentage from direct Franchisee Total Funds - 0.50%
●  Percentage from direct Premium from Franchisee Total Funds - 0.20%
●  Percentage from direct direct Master Franchisee Total Funds - 0.10%
●  For each card combo (digital+physical) sold to direct members - 50 USD
●  For each Digital Card sold - 30 USD
●  For each Physical Card Sold - 20 USD`,
      note: 'Note :',
      noteText: `1. The public price is 140 USD per digital card and 60 USD per physical card and 200 USDT if
you purchase the combo.
\n2. The upgrade from general public to Franchisee, Premium Franchisee and Master Franchisee
will take place manually from Triskel ́s admin panel as discussed.`,
      signcontract: 'Please sign the contract',
      terms: 'I accept all the terms and conditions.',
    },
    transactionHistory: {
      send: 'Send',
      receive: 'Receive',
      swap: 'Swap',
      transaction: "Transaction"
    },
    makerchecker: {
      selectChain: 'Select Chain',
      importUsingSeedPhrase: 'Import Using SeedPhrase',
      createMarkerWallet: 'Create Maker Wallet',
      createMakerAccount: 'Create Maker Account',
      askingAccess: "Asking for Access",
      requestSubheadingnote: "wants to get the Maker Account Access of your",
      signYourTransaction: "Sign Your Transaction",
      walletAddress: "Wallet Address",
      walletName: "Wallet Name",
      enterWalletName: "Enter Wallet Name",
      asset: "Asset",
      from: "From",
      to: "To",
      networkFee: "Network Fee",
      maxTotal: "Max Total",
      checkerAsset: "Checker Assets Key",
      approveYourTransaction: 'Approve Your Transaction'
    },
    makerChecker: {
      selectChain: 'Select Chain',
      keyWallet: 'Qubetics Wallet',
      BTCCode: 'BTC Code',
      ETHCode: 'ETH Code',
      TRONCode: 'TRON Code',
      BSCCode: 'BSC Code',
      refresh: 'Refresh',
      accessSuccess: 'Your wallet access request has been accepted.',
      accessRejected: 'Your wallet access request has been rejected.'
    },
    changellyBuySell: {
      youPay: 'You Pay',
      youReceive: 'You Receive',
      youSell: 'You Sell',
      getOffers: 'Get offers',
      pleaseSelectCountryFirst: "Please select a country first",
      pleaseSelectCurrenciesFirst: "Please select currencies first",
      pleaseSelectCryptocurrencyFirst: "Please select a cryptocurrency first"
    },
    nftData: {
      Nfts: "NFT’s",
      ReceiveNft: "Receive NFT",
      yourQubeticsAddress: "Your Qubetics Address",
      ownerAddress: "Owner Address",
      contactAddress: "Contact Address",
      tokenID: "Token ID",
      tokenStandard: "Token Standard.",
      Quantity: "Quantity",
      ArchitecturalStyle: "Architectural Style",
      Years: "Years",
      Country: "Country",
      nftDetailDesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy ",
      sendNFT: "Send NFT",
      Standard: "Standard",
      enterAddress: "Enter Address",
      availableNFT: "Available NFT’s",
      transactionFees: " Transaction Fees",
      Confirm: "Confirm",
      noNftFound: "No Data Found",
    }
  },


});
