import LocalizedStrings from 'react-native-localization';
import { Colors, Images } from './src/theme';
import colors from './src/theme/Colors';
export const ThemeManager = new LocalizedStrings({
      //light Mode Ui
      lightMode: {
            colors: {
                  theme: 'light',
                  notiBg: '#1A202E',
                  borderColor11: 'rgba(161, 161, 161, 1)',
                  cardBg1: Colors.White,
                  newTint: '#1A202E',
                  ios: 'rgba(216, 226, 236,1)',
                  android: 'rgba(216, 226, 236,1)',
                  newPie: Colors.White,
                  addressBookBg: 'rgba(216, 226, 236,0.5)',
                  rangeTxt: '#09090A',
                  horizontalLine: '#F1F5F9',
                  toastBg: '#1A202E',
                  bottomColor: '#FFFFFF',
                  txtNew1: '#64748B',
                  txtNew2: '#64748B',
                  cardBg: '#F1F1F1',
                  txtColor: '#8B9CB5',
                  bgNew: '#fff',
                  bg: '#031346',
                  statusBarColor1: '#1A202E',
                  addressModalBg: '#F1F5F9',
                  contactBg: '#D8E2EC',
                  activeTab: '#1A202E',
                  inActiveTabText: '#1A202E',
                  pieBg: Colors.White,
                  pieInnerColor: Colors.White,
                  txtTitle: '#212730',
                  safeBottom: Colors.White,
                  modalCard: '#F0F9FC',
                  buttonBg: '#1A202E',
                  borderUnderLine: '#D8E2EC',
                  bgQr: '#60D2D3',
                  newTitle: '#1A202E',
                  subTitle: '#64748B',
                  subTitle1: '#64748B',
                  Text: '#F1F5F9',
                  walletCardBg: '#F1F5F9',
                  searchBg: '#F1F5F9',
                  borderColor1: '#D8E2EC',
                  statusBarColor: '#1A202E',
                  groupTransferTxt: 'rgba(161, 161, 161, 1)',
                  manageToViewbg: '#FFFFFF',
                  manageWalletModalBg: '#FFFFFF',
                  Mainbg: '#030D0D',
                  MainbgNew: Colors.White,
                  colorVariation: 'rgba(36, 160, 157, 1)',
                  colorVariationBorder: '#1A202E',
                  lightBlack: '#fff',
                  lightBlackNew: '#F0F3F7',
                  newLightBlack: '#030D0D',
                  lightSettingBG: '#F0F3F7',
                  grayColor: '#DDDDDD',
                  transparent: '#00000066',
                  Linear2: '#373737',
                  DarkGreen: '#46CB6B',
                  DarkRed: '#ff1111',
                  tabBottomColor: '#272627',
                  qrCodeColor: '#B3B3B3',
                  whiteText: '#000',
                  pinCodeText: '#fff',

                  blackText: Colors.White,
                  lightWhiteText: '#8B9CB5',
                  lightWhiteTextNew: '#A1A1A1',
                  newBorderColor: '#A1A1A1',
                  textColor: Colors.White,
                  textColorNew: '#000',
                  placeholderColor: Colors.White,
                  textInputBorderColor: '#A1A1A1',
                  welcomeCommaName: '#09090A',
                  urlLinkColor: '#a7a7a7',
                  defi_btn_color: '#363536',
                  inputMainColor: 'black',
                  advanceModeDialogBorder: '#a7a7a7',
                  passPhraseTitle: '#738deb',
                  greytoken_type: '#A1A1A1',
                  darkMode: 'black',
                  borderColor: '#76747B',
                  cellColor: 'rgba(95,94,94,0.41)',
                  borderColorWallet: 'rgba(38, 58, 88, 0.5)',
                  borderColorCurr: 'rgba(200, 200, 200, 0.3)',
                  text_color: '#000',
                  hedingTextColor: '#09090A',
                  lightGrayTextColor: '#A1A1A1',
                  lightText: '#56828E',
                  viewBg: '#E6EBF1',
                  settingsText: '#00BEF2',
                  underLineColor: '#D8E2EC',
                  settingBg: '#F1F5F9',
                  text_Color: '#212730',
                  new_BorderColor: '#E1E1E1',
                  lighttextnew: '#AAB2BB',
                  newBg: Colors.White,
                  newTxt: '#60809F',
                  light_Txt: 'rgba(26, 24, 24, 0.5)',
                  txtNew: '#4B515A',
                  lightWhiteTextNew: 'rgba(255,255,255,0.8)',
                  borderNew: 'rgba(112,112,112,0.5)',
                  iconTint: 'black',
                  bottomSheetColor: '#fff',
                  alertText: '#1A202E',
                  subTextColor: '#FFFFFF',
                  TextColor: '#737373',
                  gradientOne: '#90E6FE',
                  gradientTwo: '#C5F2FF',
                  gradientThree: '#D8F7FF',
                  dividerColor: '#737373',
                  sheetTopLine: '#9ECFDC',
                  modalBg: '#00000099',
                  nmemonicsInputColor: '#FFFFFF',
                  blackWhite: '#000000',
                  textColorLight: '#57838f',
                  walletTokenBg: '#ECFBFF',
                  lightBlue: '#F0F9FC',
                  cloudy: '#56828E',
                  gradientColoTwo: ['#69DADB00', '#69DADB1A'],
                  gradientColorNew: ['#031346', '#0C2121'],
                  gradientColorTest: ['#031346', '#0C2121'],
                  gradientColorText: colors.gradientColorText,
                  placeHolderText: colors.placeHolderText,
                  //////  //////////////
                  ButtonLin: ['#24A09D', '#69DADB'],
                  buttonText: '#030D0C',
                  textColor: '#E5E5E5',
                  headersTextColor: '#FFFFFF',
                  carBorder: '#101010',
                  inputBorder: '#071818',
                  inputPlace: '#A4B1B4',
                  pinBackground: '#071818',
                  pasteInput: '#24A09D',
                  cardCur: '#737373',
                  cardSky: '#69DADB',
                  max: '#5ED1D2',
                  tabInactive: '#737373',
                  primaryColor: '#7DB0FF',
                  coinNameText: '#FFFFFF',
                  text24Hours: '#8F9495',
                  bottomColor1: "rgba(105, 218, 219, 0.12)",
                  bottomColor2: "rgba(3, 13, 13, 1)",
                  bottomColor3: "rgba(105, 218, 219, 0.12)",
                  modalBgNew: colors.modalBgNew,
                  greenText: "#6BD99C",
                  blurBg: colors.blurBg,
                  gradientOneColor: "rgba(105, 218, 219, 0)",
                  gradientTwoColor: 'rgba(255, 255, 255, 1)',
                  gradientThreeColor: 'rgba(105, 218, 219, 0.2)',
                  greyText: 'rgba(115, 115, 115, 1)',
                  placeholderColorNew: 'rgba(83, 96, 99, 1)',
                  charColor: '#1BDBF6',
                  dropDownColor: 'rgba(129, 134, 134, 1)',


                  headingText: '#D0D3DA',
                  greyNotificationtext: 'rgba(84, 101, 115, 1)',
                  addressBookDropColor: 'rgba(21, 27, 27, 1)',
                  addressBookDropBorederColor: 'rgba(41, 41, 41, 1)',
                  sendAddressBg: '#60D2D333',
                  tabsInactiveColor: '#424A4A',

                  ///////////////Light Mode
                  mainBgNew: 'rgba(244, 245, 247, 1)',
                  blackWhiteText: "rgba(0, 0, 0, 1)",
                  whiteBlacktext: "#F4F5F7",
                  greenWhite: '#60D2D3',
                  grayBlack: "rgba(11, 11, 11, 1)",
                  placeholderBg: "#FFFFFF",
                  pinBgWhiteBlack: "#FFFFFF",
                  darkLighttext: '#506064',
                  tabBarBgColor: "#ECEFF8",
                  grayIconColor: "#818686",
                  grayTextColor: "#00000080",
                  searchBorderColor: '#D9DADA',
                  blackWhitePure: "#000000",
                  whiteBlackPure: "#000000",
                  redColor: "#FF3E41",
                  greenColor: "#56B52A",
                  dividerColorNew: "#E6E6E6",
                  borderBlackGray: "#000000",
                  circleGadientBg: ['#fff', '#EBFAFA'],
                  mode: "light",
                  btcBgColor: "#F4EBE1",
                  ethBgColor: "#ECEFF8",
                  solanaBg: "#EDE5F6",
                  tetherBg: "#E4EEED",
                  headerBgGradient: ["#FFFFFF", "#E6F9F9"],
                  safeAreaBgGradient: ["#E6F9F9", "#E6F9F9", "#FFFFFF"],
                  addressBgGradient: ["#D7F7F7", "#D7F7F7", "#D7F7F7",],
                  modalBgLatest: "#FFFFFF",
                  dividernew: "#E6E6E6",
                  subCardBgColor: "#F4F5F7",
                  pinColor: "#000000",
                  pinColor2: 'rgba(115, 115, 115, 0.5)',
                  dropDownClr: ["#69DADB00", "#69DADB33"],
                  lineColor: '#E6E6E6',
                  statusBg: ['red', 'red', 'red'],
                  statusBgDark: ['black', 'black', 'black'],
                  lightBorderColor: "#506064",
                  grayBlackNew: "#DDDDDD",
                  gradientColorCard: ["#D7F7F7", "#FFFFFF",],
                  modalBorder: '#2A355B',
                  tabBgColor: '#D7F7F7',



                  // new colors added 
                  legalGreyColor: "#98969B",
                  legalBg: "#1A202E",
                  mnemonicsBg: "#18171F",
                  mnemonicsBorder: "#1D272E",
                  darkGreyBg: "#15141A",
                  darkBg: "#040205",
                  settingIconsBg: "#2C2A37",
                  inputBgNew: "#110F15",
                  greenText: "#6BD99C",
                  transactionIconBg: "#1E2930",
                  lightGreyText: "#CFD3E1",

            },
            ImageIcons: {
                  appIcon: Images.portfolio,
                  dashBActive: Images.dashboard_active,
                  dashBInActive: Images.dashboard_inactive,
                  swapInactive: Images.swap_inactive,
                  swapActive: Images.swap_active,
                  portfolio: Images.portfolio,
                  otcActive: Images.dapp_active,
                  otcInactive: Images.dappInActiveLight,
                  settingActive: Images.setting_active,
                  settingsInactive: Images.setting_inactive,
                  manage: Images.ManageIconNew,
                  priceAlert: Images.PriceAlertIcon,
                  search: Images.searchNew,
                  history: Images.HistoryIcon,
                  dropDown: Images.DownArrow,
                  scan: Images.Scan,
                  toggleGreen: Images.toggleGreen,
                  toggleOff: Images.ToggleOff,
                  fav: Images.fav,
                  unFav: Images.unfav,
                  copy: Images.copyNew,
                  share: Images.Share,
                  loader: Images.loader,
                  addressBook: Images.addressBook,
                  bin: Images.bin,
                  noPriceAlert: Images.noPriceAlert,
                  cancel: Images.CancelIcon,
                  walletManage: Images.walletManage,
                  appLogo: Images.appLogo,
                  deposit: Images.deposit,
                  withdraw: Images.withdrawNew,
                  radioActive: Images.road,
                  radioInactive: Images.roadinactive,
                  review: Images.review,
                  toggle: Images.swapLights,
                  arrowLong: Images.ArrowLong,
                  fb: Images.fb,
                  google: Images.google,
                  apple: Images.apple,
                  linkedIn: Images.linkedIn,
                  mail: Images.mail,
                  noContact: Images.noContactLight,
                  // **************
                  welcomelogo: Images.welcomelogo,
                  safeIcon: Images.safeIcon,
                  checked: Images.checked,
                  blackBack: Images.blackBack,
                  forwardIcon: Images.forwardIcon,
                  paste: Images.paste,
                  alertsecret: Images.alertsecret,
                  bullet: Images.bullet,
                  smallAlert: Images.smallAlert,
                  manageFutureLogo: Images.manageFutureLogo,
                  infoIcon: Images.infoIcon,
                  deleteIcon: Images.deleteIcon,
                  dappForward: Images.dappForward,
                  managenew: Images.managenew,
                  toggleNewIcon: Images.toggleNewIcon,
                  RightArrow: Images.RightArrow,
                  tickIcon: Images.tickIcon,
                  referralRewardIcon: Images.referralRewardIcon,
                  futureLogo: Images.futureLogo,
                  portfolioIcon: Images.portfolioIcon,
                  swapIconNew: Images.swapIconNew,
                  receiveIconNew: Images.receiveIconNew,
                  sendIconNew: Images.sendIconNew,
                  mainBgImg: Images.mainBgImg,
                  logoTextImg: Images.logoTextImg,
                  cardViewImg: Images.cardViewImgLight,
                  cardImportBg: Images.cardViewImgLight,


                  // *********Setting icons ********
                  rightArrow: Images.rightArrowDark,
                  lockIcon: Images.lockIconLight,
                  biometricNew: Images.biometricLight,
                  manageWalletLogo: Images.manageWalletLogo,
                  alertIcon: Images.alertIcon,
                  aboutUs: Images.aboutUs,
                  privacyPolicy: Images.privacyPolicy,
                  transactionHistory: Images.transactionHistory,
                  cardCross: Images.crossIconLight,
                  rightArrowLong: Images.rightArrowLong,
                  backupMnemonics: Images.backupMnemonics,
                  backupPrivateKey: Images.backupPrivateKey,
                  manageAlertIcon: Images.manageAlertIcon,

                  qrBackGround: Images.ic_qr_bgLight,
                  charBgImg: Images.charBgImg,

                  unCheckedIcon: Images.unCheckedIcon,
                  checkedIcon: Images.checkedIcon,
                  walletNameBg: Images.walletNameBgLight,
                  slippageIcon: Images.slippageIcon,
                  sendCardMain: Images.gradientWhiteCard,

                  ////lightmde Images 



                  // ********************** Theme Light ****************************

                  mainBgImgNew: Images.mainBgImgNew,
                  logoLight: Images.logoLight,
                  headerBackground: Images.gradientWhiteCard,
                  arrowRight: Images.arrowRightDark,
                  homeSubBg: Images.homeSubBackgroundLight,
                  searchIcon: Images.searchGreen,
                  addPeopleicon: Images.addPeopleLight,
                  manageIcon: Images.twoLineLight,
                  searchWallet: Images.searchLightWallet,
                  darkLightCardImg: Images.singleCardLight,
                  portfolioIconNew: Images.portfolioLight,
                  approxEqual: Images.approxEqualIconLight,
                  addressCopyIcon: Images.addressCopyLight,
                  shareIcon: Images.shareIconLight,
                  swapIconNew: Images.swapIcon,
                  manageAccountIcon: Images.manageIconDark,
                  securityIcon: Images.security,
                  nativeCurrency: Images.nativeCurrency,
                  logOutIcon: Images.logOut,
                  activeSettingIcon: Images.activeSettingLight,
                  inActiveSetting: Images.inActiveSettingLight,
                  addressBookIcon: Images.addressBookDark,
                  portfolio_active: Images.portfolio_active,
                  prefrenceIcon: Images.prefrenceDark,
                  circleBg: Images.circleBgLight,
                  deleteIconNew: Images.deleteDarkIcon,
                  crossIconNew: Images.crossIconLight,
                  swapNew: Images.swapLightNew,
                  crossNew: Images.crossLightNew,
                  newDropDown: Images.newDropDown,
                  manageNewIcon: Images.reorderLight,
                  checkerAssetsIcon: Images.checkerAssetsIcon,
                  walletConnect: Images.walletConnect,
                  checkerKey: Images.checkerKey












            },
      },
      //dark new Mode Ui
      darkMode: {
            colors: {
                  theme: 'dark',
                  notiBg: '#1A202E',
                  borderColor11: 'rgba(161, 161, 161, 1)',
                  cardBg1: Colors.White,
                  newTint: '#1A202E',
                  ios: 'rgba(216, 226, 236,1)',
                  android: 'rgba(216, 226, 236,1)',
                  newPie: Colors.White,
                  addressBookBg: 'rgba(216, 226, 236,0.5)',
                  rangeTxt: '#09090A',
                  horizontalLine: '#F1F5F9',
                  toastBg: '#1A202E',
                  bottomColor: '#FFFFFF',
                  txtNew1: '#64748B',
                  txtNew2: '#64748B',
                  cardBg: '#F1F1F1',
                  txtColor: '#8B9CB5',
                  bgNew: '#fff',
                  bg: '#031346',
                  statusBarColor1: '#1A202E',
                  addressModalBg: '#F1F5F9',
                  contactBg: '#D8E2EC',
                  activeTab: '#1A202E',
                  inActiveTabText: '#1A202E',
                  pieBg: Colors.White,
                  pieInnerColor: Colors.White,
                  txtTitle: '#212730',
                  safeBottom: Colors.White,
                  modalCard: '#F0F9FC',
                  buttonBg: '#1A202E',
                  borderUnderLine: '#D8E2EC',
                  bgQr: '#60D2D3',
                  newTitle: '#1A202E',
                  subTitle: '#64748B',
                  subTitle1: '#64748B',
                  Text: '#F1F5F9',
                  walletCardBg: '#F1F5F9',
                  searchBg: '#F1F5F9',
                  borderColor1: '#D8E2EC',
                  statusBarColor: '#1A202E',
                  groupTransferTxt: 'rgba(161, 161, 161, 1)',
                  manageToViewbg: '#FFFFFF',
                  manageWalletModalBg: '#FFFFFF',
                  Mainbg: '#030D0D',
                  MainbgNew: Colors.White,
                  colorVariation: 'rgba(79, 83, 83, 1)',
                  colorVariationBorder: '#1A202E',
                  lightBlack: '#fff',
                  lightBlackNew: '#F0F3F7',
                  newLightBlack: '#030D0D',
                  lightSettingBG: '#F0F3F7',
                  grayColor: '#DDDDDD',
                  transparent: '#00000066',
                  Linear2: '#373737',
                  DarkGreen: '#46CB6B',
                  DarkRed: '#ff1111',
                  tabBottomColor: '#272627',
                  qrCodeColor: '#B3B3B3',
                  whiteText: '#000',
                  pinCodeText: '#000',
                  blackText: Colors.White,
                  lightWhiteText: '#8B9CB5',
                  lightWhiteTextNew: '#A1A1A1',
                  newBorderColor: '#A1A1A1',
                  textColor: Colors.White,
                  textColorNew: '#000',
                  placeholderColor: Colors.White,
                  textInputBorderColor: '#A1A1A1',
                  welcomeCommaName: '#09090A',
                  urlLinkColor: '#a7a7a7',
                  defi_btn_color: '#363536',
                  inputMainColor: 'black',
                  advanceModeDialogBorder: '#a7a7a7',
                  passPhraseTitle: '#738deb',
                  greytoken_type: '#A1A1A1',
                  darkMode: 'black',
                  borderColor: '#76747B',
                  cellColor: 'rgba(95,94,94,0.41)',
                  borderColorWallet: 'rgba(38, 58, 88, 0.5)',
                  borderColorCurr: 'rgba(200, 200, 200, 0.3)',
                  text_color: '#000',
                  hedingTextColor: '#09090A',
                  lightGrayTextColor: '#A1A1A1',
                  lightText: '#56828E',
                  viewBg: '#E6EBF1',
                  settingsText: '#00BEF2',
                  underLineColor: '#D8E2EC',
                  settingBg: '#F1F5F9',
                  text_Color: '#212730',
                  new_BorderColor: '#E1E1E1',
                  lighttextnew: '#AAB2BB',
                  newBg: Colors.White,
                  newTxt: '#60809F',
                  light_Txt: 'rgba(26, 24, 24, 0.5)',
                  txtNew: '#4B515A',
                  lightWhiteTextNew: 'rgba(255,255,255,0.8)',
                  borderNew: 'rgba(112,112,112,0.5)',
                  iconTint: 'black',
                  bottomSheetColor: '#fff',
                  alertText: '#1A202E',
                  subTextColor: '#FFFFFF',
                  TextColor: '#737373',
                  gradientOne: '#90E6FE',
                  gradientTwo: '#C5F2FF',
                  gradientThree: '#D8F7FF',
                  dividerColor: '#292929',
                  sheetTopLine: '#9ECFDC',
                  modalBg: '#00000099',
                  nmemonicsInputColor: '#101010',
                  blackWhite: '#000000',
                  textColorLight: '#57838f',
                  walletTokenBg: '#ECFBFF',
                  lightBlue: '#F0F9FC',
                  cloudy: '#56828E',
                  gradientColoTwo: ['#69DADB00', '#69DADB1A'],
                  gradientColoTwo: ['#69DADB00', '#98DB691A'],
                  gradientColorNew: ['#031346', '#0C2121'],
                  gradientColorTest: ['#031346', '#0C2121'],
                  gradientColorText: colors.gradientColorText,
                  placeHolderText: colors.placeHolderText,



                  //////  //////////////
                  ButtonLin: ['#24A09D', '#69DADB'],
                  buttonText: '#030D0C',
                  textColor: '#E5E5E5',
                  headersTextColor: '#FFFFFF',
                  carBorder: '#101010',
                  inputBorder: '#76747B',
                  inputPlace: '#536063',
                  pinBackground: '#071818',
                  pasteInput: '#24A09D',
                  cardCur: '#737373',
                  cardSky: '#69DADB',
                  max: '#5ED1D2',
                  tabInactive: '#737373',
                  primaryColor: '#7DB0FF',
                  coinNameText: '#FFFFFF',
                  text24Hours: '#8F9495',
                  bottomColor1: "rgba(105, 218, 219, 0.12)",
                  bottomColor2: "rgba(3, 13, 13, 1)",
                  bottomColor3: "rgba(105, 218, 219, 0)",
                  modalBgNew: colors.modalBgNew,
                  blurBg: colors.blurBg,

                  gradientOneColor: "rgba(105, 218, 219, 0)",
                  gradientTwoColor: 'rgba(16, 16, 16, 1)',
                  gradientThreeColor: 'rgba(105, 218, 219, 0.2)',
                  greyText: 'rgba(115, 115, 115, 1)',
                  placeholderColorNew: 'rgba(83, 96, 99, 1)',
                  charColor: '#1BDBF6',
                  dropDownColor: 'rgba(129, 134, 134, 1)',

                  headingText: '#D0D3DA',
                  greyNotificationtext: 'rgba(84, 101, 115, 1)',
                  addressBookDropColor: 'rgba(21, 27, 27, 1)',
                  addressBookDropBorederColor: 'rgba(41, 41, 41, 1)',
                  sendAddressBg: '#60D2D333',
                  tabsInactiveColor: '#424A4A',

                  /////// darakMode
                  mainBgNew: '#101010',
                  blackWhiteText: "#FFFFFF",
                  whiteBlacktext: "#030D0D",
                  greenWhite: '#F4F5F7',
                  grayBlack: "#D0D3DA",
                  placeholderBg: "#98969B",
                  pinBgWhiteBlack: "#98969B",
                  darkLighttext: '#737373',
                  //      tabBarBgColor: ["rgba(105, 218, 219, 0)" , "rgba(3, 13, 13, 1)","rgba(105, 218, 219, 0.12)"  ]
                  // tabBarBgColor: ["rgba(105, 218, 219, 0.08)", "rgba(3, 13, 13, 1)", "rgba(105, 218, 219, 0.08)"],
                  tabBarBgColor: "#121117",


                  grayIconColor: "#818686",
                  grayTextColor: "#FFFFFF80",
                  searchBorderColor: '#292929',
                  blackWhitePure: "#ffffff",
                  whiteBlackPure: "#000000",
                  redColor: "#FF3E41",
                  greenColor: "#56B52A",
                  dividerColorNew: "#DCE2F5",
                  borderBlackGray: "#536063",
                  circleGadientBg: ['#69DADB33', '#69DADB00'],
                  mode: "dark",
                  btcBgColor: "#1B1A0E",
                  ethBgColor: "#192225",
                  solanaBg: "#141423",
                  tetherBg: "#0A1C1A",
                  headerBgGradient: ["#101010", "#1F3131"],
                  safeAreaBgGradient: ["#101010", "#1F3131", "#101010",],
                  addressBgGradient: ["#203333", "#203333", "#203333",],
                  modalBgLatest: "#030D0D",
                  dividernew: "#DCE2F526",
                  subCardBgColor: "#69DADB1A",

                  pinColor: "#F4F5F7",
                  pinColor2: 'rgba(115, 115, 115, 0.5)',
                  dropDownClr: ["#15141A", "#15141A"],
                  lineColor: '#292929',
                  statusBg: ['red', 'red', 'red'],
                  statusBgDark: ['black', 'black', 'black'],
                  lightBorderColor: "#737373",
                  grayBlackNew: "#00000066",
                  gradientColorCard: [' rgba(105, 218, 219, 0.2)', 'rgba(16, 16, 16, 1)'],
                  modalBorder: '#2A355B',
                  tabBgColor: '#071818',


                  // new colors added 
                  legalGreyColor: "#98969B",
                  legalBg: "#1A202E",
                  mnemonicsBg: "#18171F",
                  mnemonicsBorder: "#1D272E",
                  darkGreyBg: "#15141A",
                  darkBg: "#040205",
                  settingIconsBg: "#2C2A37",
                  inputBgNew: "#110F15",
                  greenText: "#6BD99C",
                  transactionIconBg: "#1E2930",
                  lightGreyText: "#CFD3E1",
                  grayGreyBorder: "#424048",
                  watchListInactiveStar: "#313038",




            },
            ImageIcons: {
                  appIcon: Images.portfolio,
                  dashBActive: Images.dashboard_active,
                  dashBInActive: Images.dashboard_inactive,
                  swapInactive: Images.swap_inactive,
                  swapActive: Images.swap_active,
                  portfolio: Images.portfolio,
                  otcActive: Images.dapp_active,
                  otcInactive: Images.dapp_inactive,
                  settingActive: Images.setting_active,
                  settingsInactive: Images.setting_inactive,
                  manage: Images.ManageIconNew,
                  priceAlert: Images.PriceAlertIcon,
                  search: Images.searchNew,
                  history: Images.HistoryIcon,
                  dropDown: Images.DownArrow,
                  scan: Images.Scan,
                  toggleGreen: Images.toggleGreen,
                  toggleOff: Images.ToggleOff,
                  fav: Images.fav,
                  unFav: Images.unfav,
                  copy: Images.copyNew,
                  share: Images.Share,
                  loader: Images.loader,
                  addressBook: Images.addressBook,
                  bin: Images.bin,
                  noPriceAlert: Images.noPriceAlert,
                  cancel: Images.CancelIcon,
                  walletManage: Images.walletManage,
                  appLogo: Images.appLogo,
                  deposit: Images.deposit,
                  withdraw: Images.withdrawNew,
                  radioActive: Images.road,
                  radioInactive: Images.roadinactive,
                  review: Images.review,
                  toggle: Images.Swap_bg,
                  arrowLong: Images.ArrowLong,
                  fb: Images.fb,
                  google: Images.google,
                  apple: Images.apple,
                  linkedIn: Images.linkedIn,
                  mail: Images.mail,
                  noContact: Images.noContact,
                  // **************
                  welcomelogo: Images.welcomelogo,
                  safeIcon: Images.safeIcon,
                  checked: Images.checked,
                  blackBack: Images.blackBack,
                  forwardIcon: Images.forwardIcon,
                  paste: Images.paste,
                  alertsecret: Images.alertsecret,
                  bullet: Images.bullet,
                  smallAlert: Images.smallAlert,
                  manageFutureLogo: Images.manageFutureLogo,
                  infoIcon: Images.infoIcon,
                  deleteIcon: Images.deleteIcon,
                  dappForward: Images.dappForward,
                  managenew: Images.managenew,
                  toggleNewIcon: Images.toggleNewIcon,
                  RightArrow: Images.RightArrow,
                  tickIcon: Images.tickIcon,
                  referralRewardIcon: Images.referralRewardIcon,
                  futureLogo: Images.futureLogo,
                  portfolioIcon: Images.portfolioIcon,
                  swapIconNew: Images.swapIconNew,
                  receiveIconNew: Images.receiveIconNew,
                  sendIconNew: Images.sendIconNew,
                  mainBgImg: Images.mainBgImg,
                  mainBgImgNew: Images.mainBgImg,

                  logoTextImg: Images.logoTextImg,
                  cardViewImg: Images.cardViewImg,
                  headerBackground: Images.cardViewImgLight,
                  cardImportBg: Images.cardImportBg,



                  // *********Setting icons ********
                  rightArrow: Images.rightArrow,
                  lockIcon: Images.lockIcon,
                  biometricNew: Images.biometricNew,
                  manageWalletLogo: Images.manageWalletLogo,
                  alertIcon: Images.alertIcon,
                  // security: Images.security,
                  aboutUs: Images.aboutUs,
                  privacyPolicy: Images.privacyPolicy,
                  transactionHistory: Images.transactionHistory,
                  cardCross: Images.cardCross,
                  rightArrowLong: Images.rightArrowLong,
                  backupMnemonics: Images.backupMnemonics,
                  backupPrivateKey: Images.backupPrivateKey,
                  manageAlertIcon: Images.manageAlertIcon,
                  qrBackGround: Images.ic_qr_bg,
                  charBgImg: Images.charBgImg,
                  unCheckedIcon: Images.unCheckedIcon,
                  checkedIcon: Images.checkedIcon,
                  walletNameBg: Images.walletNameBg,
                  slippageIcon: Images.slippageIcon,
                  sendCardMain: Images.sendCardMain,

                  // ********************** Theme Dark ****************************


                  logoLight: Images.logo,
                  headerBackground: Images.headerBackground,
                  arrowRight: Images.arrowRight,
                  homeSubBg: Images.homeSubBackground,
                  searchIcon: Images.SearchWhite,
                  addPeopleicon: Images.addPeople,
                  manageIcon: Images.manageButtonIcon,
                  searchWallet: Images.searchDarkWallet,
                  darkLightCardImg: Images.singleCard,
                  portfolioIconNew: Images.portfolio,
                  approxEqual: Images.approxEqualIconDark,
                  addressCopyIcon: Images.address_copy,
                  shareIcon: Images.share_icon_new,
                  swapIconNew: Images.swapIcon,
                  manageAccountIcon: Images.manageIconDark,
                  securityIcon: Images.security,
                  nativeCurrency: Images.nativeCurrency,
                  logOutIcon: Images.logOut,
                  activeSettingIcon: Images.activeSettingDark,
                  inActiveSetting: Images.inActiveSettingLight,
                  addressBookIcon: Images.addressBookDark,
                  portfolio_active: Images.portfolio_active,
                  prefrenceIcon: Images.prefrenceDark,
                  circleBg: Images.circleBgDark,
                  deleteIconNew: Images.delete,
                  crossIconNew: Images.crossIconDark,
                  swapNew: Images.swapDarkNew,
                  crossNew: Images.crossDarkNew,
                  newDropDown: Images.newDropDown,
                  manageNewIcon: Images.reorderLight,
                  checkerAssetsIcon: Images.checkerAssetsIcon,
                  walletConnect: Images.walletConnect,
                  checkerKey: Images.checkerKey























            },
      },

});
