require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-permissions/scripts/setup'

platform :ios, '13.0'
install! 'cocoapods', :deterministic_uuids => false

target 'QubeticsWallet' do
  config = use_native_modules!
  use_modular_headers!
  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
#  permissions_path = '../node_modules/react-native-permissions/ios/Camera'
#  pod 'Permission-Camera', :path => "#{permissions_path}/Permission-Camera.podspec"
   
   setup_permissions([
     # 'AppTrackingTransparency',
     # 'Bluetooth',
     # 'Calendars',
     # 'CalendarsWriteOnly',
      'Camera',
     # 'Contacts',
      'FaceID',
     # 'LocationAccuracy',
     # 'LocationAlways',
     # 'LocationWhenInUse',
     # 'Microphone',
     # 'Motion',
      'Notifications',
      'PhotoLibrary',
     # 'PhotoLibraryAddOnly',
     # 'Reminders',
     # 'Siri',
     # 'SpeechRecognition',
     # 'StoreKit',
   ])
   
   pod 'react-native-charts-wrapper', :path => '../node_modules/react-native-charts-wrapper'
   # pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'
   pod 'react-native-randombytes', :path => '../node_modules/react-native-randombytes'

   pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

   pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  #  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

   pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

   pod 'react-native-config', :path => '../node_modules/react-native-config'

   pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'

  #  pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  pod 'TrustWalletCore'
   pod 'HDWalletKit'
   pod 'HDWalletKitBTC', :path => './'


  target 'QubeticsWalletTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
